### ISSUE TITLE
ToggleGroup is not defined for DetailField

### ISSUE THREAD

**Issue by mrdj07** [stepanenko3/nova-boolean-group-field#2]
https://github.com/stepanenko3/nova-boolean-group-field/blob/83c52b19f076ba38f3fb34a4c8acfb3cf1712869/resources/js/components/DetailField.vue#L9

**Comment by stepanenko3** [comment]
Hi, @mrdj07 

Fixed in https://github.com/stepanenko3/nova-boolean-group-field/releases/tag/v1.0.2
